"""empty message

Revision ID: 313e75a13c98
Revises: eade0afec76f
Create Date: 2024-06-05 15:32:42.870166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313e75a13c98'
down_revision = 'eade0afec76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
