"""empty message

Revision ID: 4d6f4c4c327e
Revises: 4fd9de6c89d3
Create Date: 2024-06-24 11:08:45.879072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6f4c4c327e'
down_revision = '4fd9de6c89d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('returned_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('returned_time')
        batch_op.drop_column('returned_by')

    # ### end Alembic commands ###
