"""empty message

Revision ID: 4fd9de6c89d3
Revises: f146cc0a6f54
Create Date: 2024-06-24 09:37:39.607149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd9de6c89d3'
down_revision = 'f146cc0a6f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('checked_out_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testlines', schema=None) as batch_op:
        batch_op.drop_column('checked_out_time')
        batch_op.drop_column('checked_out_by')

    # ### end Alembic commands ###
