"""empty message

Revision ID: 79aa4705cd08
Revises: ba055c16f47b
Create Date: 2024-06-19 10:54:16.934855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79aa4705cd08'
down_revision = 'ba055c16f47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serialNumber', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('productName', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('siteId', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('storageLocation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('itemOwner', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nokiaSto', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('serial')
        batch_op.drop_column('model')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('model', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('serial', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('nokiaSto')
        batch_op.drop_column('itemOwner')
        batch_op.drop_column('storageLocation')
        batch_op.drop_column('siteId')
        batch_op.drop_column('productName')
        batch_op.drop_column('serialNumber')

    # ### end Alembic commands ###
