"""empty message

Revision ID: b4c6217062a0
Revises: 4d6f4c4c327e
Create Date: 2024-06-24 11:39:46.113410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c6217062a0'
down_revision = '4d6f4c4c327e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('returned_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testlines', schema=None) as batch_op:
        batch_op.drop_column('returned_time')
        batch_op.drop_column('returned_by')

    # ### end Alembic commands ###
