"""empty message

Revision ID: f146cc0a6f54
Revises: 
Create Date: 2024-06-19 16:22:36.110658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f146cc0a6f54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('can_manage_tools', sa.Boolean(), nullable=True),
    sa.Column('can_manage_testlines', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('testline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['testline_id'], ['testlines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('serialNumber', sa.String(), nullable=True),
    sa.Column('productName', sa.String(), nullable=True),
    sa.Column('productId', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('siteId', sa.String(), nullable=True),
    sa.Column('storageLocation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('itemOwner', sa.String(), nullable=True),
    sa.Column('nokiaSto', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tools')
    op.drop_table('reservations')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('testlines')
    # ### end Alembic commands ###
